export const SEED_MONEY = 100_000_000
export const STOCK_COUNT = 100
export const TRADING_RATIO = 1
export const CASH_RESERVE_RATIO = 5
export const MAXIMUM_CASH_RESERVE_RATIO = 10

export const PORTFOLIO_DISTRIBUTION_FIXED_RATIO =
  (SEED_MONEY * (1 - CASH_RESERVE_RATIO / 100)) / STOCK_COUNT
export const COMMISION = 0.0043319
export const COMMISION_RATIO = (COMMISION * 100) / TRADING_RATIO
export const INITIAL_CASH_RESERVES = Math.floor(SEED_MONEY * (CASH_RESERVE_RATIO / 100))
export const INITIAL_BALANCE = SEED_MONEY - INITIAL_CASH_RESERVES
